version: '3.7'
services:
    astro-mysql-database:
      build:
        context: Database/astro-mysql-database
        dockerfile: Dockerfile
      ports:
        - "3306:3036"
      env_file:
        - ./config/database.env
      volumes:
        - ./Database/mysql-volume:/var/lib/mysql
      networks:
        - astro-backend-networks
    astro-admin-backend:
      build:
        context: Services/admin/astro-backend
        dockerfile: Dockerfile
      restart: always
      ports:
        - "3001:3001"
        - "5555:5555"
      env_file:
        - ./config/backend.env
      volumes:
        - "./Services/admin/astro-backend/:/usr/astro-backend"
      networks:
        - astro-backend-networks
    astro-admin-frontend:
      build:
        context: Frontends/admin/astro-admin-frontend
        dockerfile: Dockerfile
      restart: always
      ports:
        - "3000:3000"
      env_file:
        - ./config/frontend.env
      volumes:
        - "./Frontends/admin/astro-admin-frontend/:/usr/astro-admin-frontend"
      networks:
        - astro-backend-networks

volumes:
    mysql-volume:
networks:
  astro-backend-networks: 