version: '3.7'
services:
    astro-admin-backend:
      build:
        context: Services/admin/astro-backend
        dockerfile: Dockerfile
      restart: always
      ports:
        - "3001:3001"
        - "5555:5555"
      env_file:
        - ./config/backend.env
      volumes:
        - "./Services/admin/astro-backend/:/usr/astro-backend"
      # environment:
      #   MYSQL_HOST: mysql
      #   MYSQL_USER: root
      #   MYSQL_PASSWORD: <your-password>
      #   MYSQL_DB: todos
    astro-mysql-database:
        image: astro-mysql-database
        ports:
            - "3306:3036"
        environment:
            MYSQL_ROOT_PASSWORD: astro
            MYSQL_DATABASE: astro
            MYSQL_USER: astro
            MYSQL_PASSWORD: astro
        volumes:
             - ./Database/mysql-volume:/var/lib/mysql
volumes:
    mysql-volume: